### ISSUE TITLE
Issue with FITS header.update(...) (Pyfits 3.4)

### ISSUE THREAD

**Issue by AlecThomson** [brentjens/rm-synthesis#1]
I get the following error when attempting to run rmsynthesis using the files located in testdata/ :
```
Traceback (most recent call last):
  File "/Users/alecthomson/anaconda2/bin/rmsynthesis", line 412, in <module>
    exit(main(sys.argv))
  File "/Users/alecthomson/anaconda2/bin/rmsynthesis", line 402, in main
    args.maxmem)
  File "/Users/alecthomson/anaconda2/lib/python2.7/site-packages/rmsynthesis/main.py", line 526, in rmsynthesis_dirty_lowmem_main
    output_header = add_phi_to_fits_header(q_header.copy(), phi_rad_m2)
  File "/Users/alecthomson/anaconda2/lib/python2.7/site-packages/rmsynthesis/main.py", line 429, in add_phi_to_fits_header
    fhdr.update('NAXIS3', len(phi_array))
  File "/Users/alecthomson/anaconda2/lib/python2.7/site-packages/pyfits/header.py", line 1017, in update
    'value, and comment string.' % idx)
ValueError: Header update sequence item #0 is invalid; the item must either be a 2-tuple containing a keyword and value, or a 3-tuple containing a keyword, value, and comment string.
```

I believe this is caused by change in the syntax in Pyfits 3.4 (and AstroPy), where now the use of header.update(...) is deprecated.

**Comment by brentjens** [comment]
Dear Alec,

thank you for spotting this. I think I have fixed it now. Could you
please try again?

- Michiel


Alec Thomson writes:

> I get the following error when attempting to run rmsynthesis using the files located in testdata/ :
> ```
> Traceback (most recent call last):
>   File "/Users/alecthomson/anaconda2/bin/rmsynthesis", line 412, in <module>
>     exit(main(sys.argv))
>   File "/Users/alecthomson/anaconda2/bin/rmsynthesis", line 402, in main
>     args.maxmem)
>   File "/Users/alecthomson/anaconda2/lib/python2.7/site-packages/rmsynthesis/main.py", line 526, in rmsynthesis_dirty_lowmem_main
>     output_header = add_phi_to_fits_header(q_header.copy(), phi_rad_m2)
>   File "/Users/alecthomson/anaconda2/lib/python2.7/site-packages/rmsynthesis/main.py", line 429, in add_phi_to_fits_header
>     fhdr.update('NAXIS3', len(phi_array))
>   File "/Users/alecthomson/anaconda2/lib/python2.7/site-packages/pyfits/header.py", line 1017, in update
>     'value, and comment string.' % idx)
> ValueError: Header update sequence item #0 is invalid; the item must either be a 2-tuple containing a keyword and value, or a 3-tuple containing a keyword, value, and comment string.
> ```
>
> I believe this is caused by change in the syntax in Pyfits 3.4 (and AstroPy), where now the use of header.update(...) is deprecated.


-- 
Dr. Michiel A. Brentjens
Senior Observatory Astronomer
Astron Netherlands Institute for Radio Astronomy
Oude Hoogeveensedijk 4
7991 PD Dwingeloo
The Netherlands
Office:    (+31) (0)521 - 595 781
Reception: (+31) (0)521 - 595 100
brentjens@astron.nl
http://www.astron.nl/~brentjens/

**Comment by AlecThomson** [comment]
Hi Michiel,

Thanks for checking on this. I've just made a pull request which fixed the issue for me whilst I was offline. I hope this is useful.

Cheers,
Alec
