### ISSUE TITLE
hdu.PrimaryHDU.NumCode should now be BITPIX2DTYPE

### ISSUE THREAD

**Issue by Sunmish** [brentjens/rm-synthesis#3]
With Astropy version 2.0.3 (perhaps earlier as well, and also with newer pyfits > 3.4) I believe that astropy.io.fits.hdu.PrimaryHDU.NumCode (pyfits.hdu.PrimaryHDU.NumCode) needs to be changed to astropy.io.fits.BITPIX2DTYPE (pyfits.BITPIX2DTYPE) in `image_frames` within `fits.py`.

**Comment by brentjens** [comment]
Fixed in commit https://github.com/brentjens/rm-synthesis/commit/c5c93979b2fb76bdfa73302c7a92723ccbe521dd
